# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(default='description', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_id', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
