# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20170305_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=550),
        ),
    ]
