# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20170305_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttom',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=250),
        ),
    ]
