# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170305_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutTom',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='description',
            new_name='about_tom',
        ),
    ]
