# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20170305_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Info'},
        ),
    ]
