# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='anter_info',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='wood_info',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
