# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20170915_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='anter_info',
            new_name='antler_info',
        ),
    ]
